apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagens-pv-claim
spec:
  storageClassName: minikube-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
