apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-noticias-deployment
  annotations:
    kubernetes.io/change-cause: Initial deploy
spec:
  replicas: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: sistema-noticias
  template:
    metadata:
      name: sistema-noticias-pod
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: docker.io/aluracursos/sistema-noticias:1
          envFrom:
            - configMapRef:
                name: sistema-noticias-cm
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 80
