apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replica-set
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: docker.io/aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-noticias-cm
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: portal-noticias
