apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "sistema-noticias.fullname" . }}-st-class
provisioner: {{ .Values.volumes.class.provisioner }}
reclaimPolicy: {{ .Values.volumes.class.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumes.class.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.volumes.class.allowVolumeExpansion }}
