apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "sistema-noticias.fullname" . }}-{{ .Values.volumes.session.claimSuffix }}"
  labels:
    {{- include "sistema-noticias.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "sistema-noticias.fullname" . }}-st-class
  accessModes:
    {{- .Values.volumes.session.accessModes | toYaml | nindent 4 }}
  resources:
    {{- .Values.volumes.session.resources | toYaml | nindent 4 }}
