apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sistema-noticias.fullname" . }}
  labels:
    {{- include "sistema-noticias.labels"  . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sistema-noticias.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- .Values.autoscaling.metrics | toYaml | nindent 4 }}
  behavior:
    {{- .Values.autoscaling.behavior | toYaml | nindent 4 }}
