apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sistema-noticias.fullname" . }}-secret
  labels:
    {{- include "sistema-noticias.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env }}
    {{- $k | nindent 4 }}: {{ required "required env var not supplied" $v }}
  {{- end }}
