apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sistema-noticias.fullname" . }}
  labels:
    {{- include "sistema-noticias.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/change-cause: {{ .Chart.Version }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "sistema-noticias.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "sistema-noticias.fullname" . }}
      labels:
        {{- include "sistema-noticias.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: "{{ include "sistema-noticias.fullname" . }}-{{ .Values.volumes.images.nameSuffix }}"
          persistentVolumeClaim:
            claimName: {{ include "sistema-noticias.fullname" . }}-{{ .Values.volumes.images.claimSuffix }}
        - name: "{{ include "sistema-noticias.fullname" . }}-{{ .Values.volumes.session.nameSuffix }}"
          persistentVolumeClaim:
            claimName: {{ include "sistema-noticias.fullname" . }}-{{ .Values.volumes.session.claimSuffix }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          envFrom:
            - secretRef:
                name: {{ include "sistema-noticias.fullname" . }}-secret
          resources:
            {{- .Values.deployment.resources | toYaml | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - mountPath: {{ .Values.volumes.images.mountPath }}
              name: "{{ include "sistema-noticias.fullname" . }}-{{ .Values.volumes.images.nameSuffix }}"
            - mountPath: {{ .Values.volumes.session.mountPath }}
              name: "{{ include "sistema-noticias.fullname" . }}-{{ .Values.volumes.session.nameSuffix }}"
          livenessProbe:
            {{- .Values.deployment.livenessProbe | toYaml | nindent 12 }}
          startupProbe:
            {{- .Values.deployment.startupProbe | toYaml | nindent 12 }}
          readinessProbe:
            {{- .Values.deployment.readinessProbe | toYaml | nindent 12 }}
