apiVersion: v1
kind: Pod
metadata:
  name: portal-noticias-pod
spec:
  containers:
    - name: portal-noticias-container
      image: docker.io/aluracursos/portal-noticias:1
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
