# Default values for sistema-noticias.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 2
  minReadySeconds: 15
  resources:
    limits:
      memory: 512Mi
      cpu: "0.5"
    requests:
      memory: 256Mi
      cpu: "0.2"
  livenessProbe:
    httpGet:
      path: /
      port: 80
    failureThreshold: 3
    initialDelaySeconds: 15
    successThreshold: 1
    periodSeconds: 10
  startupProbe:
    httpGet:
      path: /
      port: 80
    failureThreshold: 15
    initialDelaySeconds: 15
    periodSeconds: 15
  readinessProbe:
    httpGet:
      path: /
      port: 80
    failureThreshold: 3
    initialDelaySeconds: 5
    successThreshold: 2
    periodSeconds: 10

image:
  repository: docker.io/aluracursos/sistema-noticias
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: NodePort
  port: 80
  nodePort: 30001
  targetPort: 80


# Create a separate values file called .env.yaml and define these vars
# The .env.yaml file is ignore by version control
env:
  HOST_DB: 'db-noticias:3306'
  USER_DB: null
  PASS_DB: null
  DATABASE_DB: empresa

volumes:
  class:
    provisioner: k8s.io/minikube-hostpath
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
  images:
    nameSuffix: imagens-pv
    claimSuffix: imagens-pv-claim
    mountPath: /var/www/html/uploads
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
  session:
    nameSuffix: sessao-pv
    claimSuffix: sessao-pv-claim
    mountPath: /tmp
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi

autoscaling:
  minReplicas: 2
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      policies:
        - periodSeconds: 60
          type: Pods
          value: 4
        - type: Percent
          value: 10
          periodSeconds: 60
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max

