apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal-noticias.fullname" . }}
  labels:
    {{- include "portal-noticias.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/change-cause: {{ .Chart.Version }}
spec:
  template:
    metadata:
      name: {{ include "portal-noticias.fullname" . }}
      labels:
        {{- include "portal-noticias.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "portal-noticias.fullname" .  }}-cm
          resources:
            {{- .Values.deployment.resources | toYaml | nindent 12 }}
          livenessProbe:
            {{- .Values.deployment.livenessProbe | toYaml | nindent 12 }}
          startupProbe:
            {{- .Values.deployment.startupProbe | toYaml | nindent 12 }}
          readinessProbe:
            {{- .Values.deployment.readinessProbe | toYaml | nindent 12 }}
  replicas: {{ .Values.deployment.replicaCount }}
  minReadySeconds: {{ .Values.deployment.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "portal-noticias.selectorLabels" . | nindent 8 }}
