apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal-noticias.fullname" . }}
  labels:
    {{- include "portal-noticias.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "portal-noticias.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
