apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "db-noticias.fullname" . }}
  labels:
    {{- include "db-noticias.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/change-cause: {{ .Chart.Version }}
spec:
  serviceName: {{ include "db-noticias.fullname" . }}
  selector:
    matchLabels:
      {{- include "db-noticias.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.statefulSet.replicaCount }}

  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ include "db-noticias.fullname" . }}-{{ .Values.volumes.db.claimSuffix }}"
        labels:
          {{- include "db-noticias.labels" . | nindent 10 }}
      spec:
        storageClassName: {{ include "db-noticias.fullname" . }}-st-class
        accessModes:
          {{- .Values.volumes.db.accessModes | toYaml | nindent 10 }}
        resources:
          {{- .Values.volumes.db.resources | toYaml | nindent 10 }}

  template:
    metadata:
      name: {{ include "db-noticias.fullname" . }}
      labels:
        {{- include "db-noticias.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.statefulSet.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - mountPath: {{ .Values.volumes.db.mountPath }}
              name: "{{ include "db-noticias.fullname" . }}-{{ .Values.volumes.db.claimSuffix }}"
          envFrom:
            - secretRef:
                name: {{ include "db-noticias.fullname" . }}-secret
          resources:
            {{- .Values.statefulSet.resources | toYaml | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            {{- .Values.statefulSet.livenessProbe | toYaml | nindent 12 }}
          readinessProbe:
            {{- .Values.statefulSet.readinessProbe | toYaml | nindent 12 }}

