apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-noticias-pv-claim
spec:
  storageClassName: minikube-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
