apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "db-noticias.fullname" . }}-secret
  labels:
    {{- include "db-noticias.labels" . | nindent 4 }}
stringData:
  {{- range $k, $v := .Values.env }}
    {{- $k | nindent 2 }}: {{ required "required env var not supplied" $v }}
  {{- end }}
