apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-noticias.fullname" . }}
  labels:
    {{- include "db-noticias.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    {{- include "db-noticias.selectorLabels" . | nindent 4 }}
