apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    app: secret-pod
spec:
  containers:
    - name: container-secret-pod
      image: nginx:latest
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      ports:
        - containerPort: 80
          name: http-port
      envFrom:
        - secretRef:
            name: db-secret
      # env:
      #   - name: username
      #     valueFrom:
      #       secretKeyRef:
      #         key: username
      #         name: db-secret
      #   - name: password
      #     valueFrom:
      #       secretKeyRef:
      #         key: password
      #         name: db-secret
