apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    app: volume-pod
    qualquer: coisa
spec:
  volumes:
    - name: primeiro-volume
      hostPath:
        path: '/data/primeiro-volume'
        type: DirectoryOrCreate
    - name: segundo-volume
      persistentVolumeClaim:
        claimName: minikube-pv-claim
  containers:
    - name: nginx-container-1
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
        - mountPath: /minikube-dynamic-volume
          name: segundo-volume
      image: nginx:latest
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
      ports:
        - containerPort: 80
          name: http-port
